//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class times_keywords_relative
    {
        public int id { get; set; }
        public int dataid { get; set; }
        public int key_id { get; set; }
        public byte type { get; set; }
        public System.DateTime add_time { get; set; }
    }
}
