//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class times_article_category
    {
        public short cat_id { get; set; }
        public string unique_id { get; set; }
        public byte type { get; set; }
        public string cat_name { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public short parent_id { get; set; }
        public short sort { get; set; }
        public System.DateTime add_time { get; set; }
    }
}
