//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Admin_Times_1Entities : DbContext
    {
        public Admin_Times_1Entities()
            : base("name=Admin_Times_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<times_admin> times_admin { get; set; }
        public DbSet<times_admin_log> times_admin_log { get; set; }
        public DbSet<times_article> times_article { get; set; }
        public DbSet<times_article_category> times_article_category { get; set; }
        public DbSet<times_config> times_config { get; set; }
        public DbSet<times_content> times_content { get; set; }
        public DbSet<times_guestbook> times_guestbook { get; set; }
        public DbSet<times_keywords> times_keywords { get; set; }
        public DbSet<times_keywords_relative> times_keywords_relative { get; set; }
        public DbSet<times_nav> times_nav { get; set; }
        public DbSet<times_page> times_page { get; set; }
        public DbSet<times_pic> times_pic { get; set; }
        public DbSet<times_product> times_product { get; set; }
    }
}
