//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class times_page
    {
        public int id { get; set; }
        public string unique_id { get; set; }
        public short parent_id { get; set; }
        public string image { get; set; }
        public string page_name { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
    }
}
